version: "3.9"
services:
  web:
    container_name: symfony-app
    build: .
    ports:
      - "8080:5000"
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "3306:${MYSQL_PORT}"
    expose:
      - "${MYSQL_PORT}"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: